version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - bookshelf:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bookshelf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "bookshelf"]
  app:
    image: book
    environment:
      - DB_HOST=database
    command:
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
volumes:
  bookshelf: